#!/usr/bin/perl

use strict;
use warnings;
use IO::Socket::INET;

my $

my $byte = 1;
my $items;
my $clsid;
my $host;

# get_socket
### param1: Host Address
### return: Socket
sub get_socket {
    my $host = $_[0];
    my $sock = IO::Socket::INET->new(PeerAddr => $host,
    Proto => 'tcp');
    return $sock;
}

sub comm_set {
    my $sock = $_[0];
    my $key = $_[1];
    my $byte = $_[2];
    my $value = 'a' x $byte;
    
    print $sock "set $key 0 0 $byte\r\n$value\r\n";
    while (<$sock>) {
        last if (/^STORED/);
    }
    return 1;
}

sub comm_del {
    my $sock = $_[0];
    my $clsid = $_[1];
    my $items = $_[2];
    
    my @keys;
    print $sock "stats cachedump $clsid $items\r\n";
    my $i = 0;
    while (<$sock>) {
        last if /^END/;
        if (/^ITEM (\S+)/) {
            $keys[$i] = $1;
        }
        $i++;
    }
    
    foreach my $key (@keys) {
        print $sock "delete $key\r\n";
        while (<$sock>) {
            last if /^DELETED/;
        }
    }
    return 1;
}

sub comm_rand {
    my $sock = $_[0];
    my $
}