#!/usr/bin/perl

use strict;
use warnings;

require "./util.pl";


my $host = shift || "localhost";
my $port = shift || "11211";
my $sock = &getSocket("$host:$port");

die "Could not connect to $host\n" unless $sock;

&commFlushAll($sock);

print "Setting...\n";

my $key_prefix = 's';
my $size = 30;
for my $n (1..200) {
    my $key = ($key_prefix).($n);
    my $res = &commSet($sock, $key, $size, 0);
    last if ($res == 0);
    $size = int($size * 1.25);
}

print "Testing...\n";

$key_prefix = 'k';
for my $m (1..1000000) {
    my $key = ($key_prefix).($m);
    &commSet($sock, $key, 10, 0);
}

__END__
