#!/usr/bin/perl

use strict;
use warnings;

require "./util.pl";

my $host = shift || "localhost";
my $port = shift || "11211";
my $sock = &getSocket("$host:$port");

die "Could not connect to $host\n" unless $sock;

&printUmemTime($sock);

__END__
